---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "default"
  name: typesense-operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: typesenseoperator-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  
  - apiGroups: [kopf.dev]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get, create]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [typesenseproject.org]
    resources: [TypesenseOperator]
    verbs: [list, watch, create]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # # Framework: admission webhook configuration management.
  # - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
  #   resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
  #   verbs: [create, patch]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "default"
  name: typesenseoperator-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [kopf.dev]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [typesenseproject.org]
    resources: [typesenseoperators]
    verbs: [list, watch, patch, create]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [pods, services]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: typesenseoperator-crolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: typesenseoperator-role-cluster
subjects:
  - kind: ServiceAccount
    name: typesense-operator-sa
    namespace: "default"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "default"
  name: typesenseoperator-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: typesenseoperator-role-namespaced
subjects:
  - kind: ServiceAccount
    name: typesense-operator-sa